services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  takjilshare:
    build: .
    restart: on-failure
    ports:
      - 11451:5000
    environment:
      MONGODB_URI: mongodb://root:example@mongodb:27017